# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#
---
include:
  - board: seeeduino_xiao_ble
    shield: mlego2x2_rev1
  - board: blackpill_f401ce 
    shield:  mlego5x13_rev4
  - board: seeeduino_xiao_rp2040
    shield: mlego2x2_rev2
  - board: rpi_pico
    shield: mlego5x13_rev5
  - board: seeeduino_xiao_rp2040
    shield: mlego5x13_rev7
  - board: seeeduino_xiao_ble
    shield: mlego5x13_rev8 rgbled_adapter
  - board: seeeduino_xiao_ble
    shield: mlego5x13_61_r8
  - board: seeeduino_xiao_ble
    shield: settings_reset
  - board: nice_nano_v2
    shield: mlego_m66_rev4 
    snippet: studio-rpc-usb-uart
  - board: nice_nano_v2
    shield: mlego_m66_rev4 ls013b7dh05 
    snippet: studio-rpc-usb-uart
  - board: nice_nano_v2
    shield: mlego_m66_rev4 ls013b7dh03s 
    snippet: studio-rpc-usb-uart
  - board: nice_nano_v2
    shield: mlego_m66_rev4 ls011b7dh03 
    snippet: studio-rpc-usb-uart
  - board: nice_nano_v2
    shield: mlego_m66_rev4 weact_eink_213 
    snippet: studio-rpc-usb-uart
  - board: nice_nano_v2
    shield: mlego_m66_rev4 weact_eink_154 
    snippet: studio-rpc-usb-uart
  - board: rpi_pico
    shield: mlego_m66_rev4_rp2040 
    snippet: studio-rpc-usb-uart
  - board: nice_nano_v2
    shield: settings_reset
  - board: rpi_pico
    shield: settings_reset
  - board: nice_nano_v2
    shield: onekey pro_micro
  - board: seeeduino_xiao_ble
    shield: onekey seed
  - board: rpi_pico
    shield: onekey rp2040
