parse_config:
  preprocess: true
  skip_binding_parsing: false
  raw_binding_map: {}
  sticky_label: $$mdi:gesture-tap-hold$$
  toggle_label: toggle
  tap_toggle_label: tap-toggle
  trans_legend:
    t: ▽
    type: trans
  mark_alternate_layer_activators: true
  modifier_fn_map:
    left_ctrl: Ctl
    right_ctrl: Ctl
    left_shift: Sft
    right_shift: Sft
    left_alt: Alt
    right_alt: AltGr
    left_gui: Gui
    right_gui: Gui
    keycode_combiner: '{mods}+ {key}'
    mod_combiner: '{mod_1}+{mod_2}'
    special_combinations:
      left_ctrl+left_alt+left_gui+left_shift: Hyper
      left_ctrl+left_alt+left_shift: Meh
  zmk_remove_keycode_prefix: []
  zmk_keycode_map:
    A:
      tap: a
      shifted: "A"
    B:
      tap: b
      shifted: "B"
    C:
      tap: c
      shifted: "C"
    D:
      tap: d
      shifted: "D"
    E:
      tap: e
      shifted: "E"
    F:
      tap: f
      shifted: "F"
    G:
      tap: g
      shifted: "G"
    H:
      tap: h
      shifted: "H"
    I:
      tap: i
      shifted: "I"
    J:
      tap: j
      shifted: "J"
    K:
      tap: k
      shifted: "K"
    L:
      tap: l
      shifted: "L"
    M:
      tap: m
      shifted: "M"
    N:
      tap: n
      shifted: "N"
    P:
      tap: p
      shifted: "P"
    Q:
      tap: q
      shifted: "Q"
    O:
      tap: o
      shifted: "O"
    R:
      tap: r
      shifted: "R"
    S:
      tap: s
      shifted: "S"
    T:
      tap: t
      shifted: "T"
    U:
      tap: u
      shifted: "U"
    X:
      tap: x
      shifted: "X"
    Y:
      tap: y 
      shifted: "Y"
    V:
      tap: v
      shifted: "V"
    W:
      tap: w
      shifted: "W"
    Z:
      tap: z
      shifted: "Z"
    
   # Numbers
    N1:
      tap: 1
      shifted: "!"
    N2:
      tap: 2
      shifted: '"'
    N3:
      tap: 3
      shifted: "£"
    N4:
      tap: 4
      shifted: "$"
    N5:
      tap: 5
      shifted: "%"
    N6:
      tap: 6
      shifted: "^"
    N7:
      tap: 7
      shifted: "&"
    N8:
      tap: 8
      shifted: "*"
    N9:
      tap: 9
      shifted: "("
    N0:
      tap: 0
      shifted: ")"

    # Symbols
    EXCLAMATION: "!"
    EXCL: "!"
    AT_SIGN: "@"
    AT: "@"
    HASH: "#"
    POUND: "#"
    DOLLAR: $
    DLLR: $
    PERCENT: "%"
    PRCNT: "%"
    CARET: ^
    AMPERSAND: "&"
    AMPS: "&"
    ASTERISK: "*"
    ASTRK: "*"
    STAR: "*"
    LEFT_PARENTHESIS: (
    LPAR: (
    RIGHT_PARENTHESIS: )
    RPAR: )
    EQUAL:
      tap: "="
      shifted: "+"
    PLUS: +
    MINUS:
      tap: "-"
      shifted: "_"
    UNDERSCORE: _
    UNDER: _
    SLASH:
      tap: "/"
      shifted: "?"
    FSLH:
      tap: "/"
      shifted: "?"
    QUESTION: "?"
    QMARK: "?"
    BACKSLASH:
      tap: '\'
      shifted: "|"
    BSLH:
      tap: '\'
      shifted: "|"
    PIPE: "|"
    NON_US_BACKSLASH: \
    PIPE2: "|"
    NON_US_BSLH: 
      tap: \
      shifted: "|"
    SEMICOLON:
      tap: ";"
      shifted: ":"
    SEMI:
      tap: ";"
      shifted: ":"
    COLON: ":"
    SINGLE_QUOTE:
      tap: "'"
      shifted: '"'
    SQT:
      tap: "'"
      shifted: '"'
    APOSTROPHE: <
    APOS: 
      tap: "'"
      shifted: "@"
    DOUBLE_QUOTES: '"'
    DQT: '"'

    LESS_THAN: <
    LT: <
    DOT:
      tap: "."
      shifted: ">"
    COMMA:
      tap: ","
      shifted: "<"
    GREATER_THAN: ">"
    GT: ">"
    LEFT_BRACKET:
      tap: "["
      shifted: "{"
    LBKT:
      tap: "["
      shifted: "{"
    LEFT_BRACE: "{"
    LBRC: "{"
    RIGHT_BRACKET:
      tap: "]"
      shifted: "}"
    RBKT:
      tap: "]"
      shifted: "}"
    RIGHT_BRACE: "}"
    RBRC: "}"
    GRAVE:
      tap: "`"
      shifted: "¬"
    TILDE: "~"
    NON_US_HASH:
      tap:  "#"
      shifted: "~"
    NUHS:
      tap:  "#"
      shifted: "~"
    TILDE2: "~"

    # Modifiers
    LCTRL: "⎈"
    LALT: "⎇"
    LSHIFT: "⇧"
    LGUI: ""
    LSHFT: "⇧"
    LCMD: $$mdi:apple-keyboard-command$$
    RCTRL: "⎈"
    RALT: "⎇"
    RSHIFT: "⇧"
    RSHFT: "⇧"
    RCMD: $$mdi:apple-keyboard-command$$
    LS(LC(LALT)): $$mdi:triangle$$ # Meh

    # Arrows
    UP: $$mdi:arrow-up-bold$$
    DOWN: $$mdi:arrow-down-bold$$
    LEFT: $$mdi:arrow-left-bold$$
    RIGHT: $$mdi:arrow-right-bold$$
    PG_UP: $$mdi:transfer-up$$
    PG_DN: $$mdi:transfer-down$$

    # Whitespace
    RET:
      type: enter
      tap: $$mdi:keyboard-return$$
    ESC: "⎋"
    TAB: "↹"
    LS(TAB): $$mdi:keyboard-tab-reverse$$
    SPACE: $$mdi:keyboard-space$$
    BACKSPACE:
      type: backspace
      tap: $$mdi:backspace$$
    BSPC:
      type: backspace
      tap: $$mdi:backspace$$
    DELETE: $$mdi:backspace-reverse-outline$$
    DEL: $$mdi:backspace-reverse-outline$$

    # Locks
    CAPSLOCK: "⇪"
    CAPS: "⇪"

    # Sound
    C_MUTE: $$mdi:volume-off$$
    C_VOL_UP: $$mdi:volume-high$$
    C_VOL_DN: $$mdi:volume-low$$
    K_MUTE: $$mdi:volume-off$$
    K_VOL_UP: $$mdi:volume-high$$
    K_VOL_DN: $$mdi:volume-low$$

    # Media
    C_NEXT: $$mdi:skip-next$$
    C_PREV: $$mdi:skip-previous$$
    C_PP: $$mdi:play-pause$$
    K_NEXT: $$mdi:skip-next$$
    K_PREV: $$mdi:skip-previous$$
    K_PP: $$mdi:play-pause$$

    # Bluetooth
    BT_CLR: $$mdi:bluetooth-off$$
    BT_SEL: $$mdi:bluetooth-connect$$

    # Settings
    C_BRI_UP: $$mdi:brightness-5$$
    C_BRI_DN: $$mdi:brightness-7$$

    # System
    C_POWER: $$mdi:power-standby$$
    C_AL_LOCK: $$mdi:lock$$
    K_CANCEL: $$mdi:close-box$$
    K_COFFEE: $$mdi:power-standby$$
    K_SLEEP: $$mdi:sleep$$
    PSCRN: $$mdi:monitor-screenshot$$
    LG(P): $$mdi:monitor-screenshot$$

  raw_binding_map:
    # Reset
    "&sys_reset":
      type: bootloader
      tap: $$mdi:backup-restore$$
    "&bootloader":
      type: bootloader
      tap: $$mdi:progress-download$$
    "&tlwr":
      tap: "⇓"
    "&trse":
      tap: "⇑"
    '&out OUT_BLE':
      tap: $$mdi:keyboard$$
      shifted: $$mdi:bluetooth$$
      type: sym_by_sym
    '&out OUT_USB':
      tap: $$mdi:keyboard$$
      shifted: $$mdi:usb$$
      type: sym_by_sym
    '&out OUT_TOG':
      tap: $$mdi:toggle-switch$$
      hold: $$mdi:bluetooth$$
      shifted: $$mdi:usb$$
      type: toggle
    '&studio_unlock':
      type: bootloader
      tap: $$mdi:android-studio$$

    '&bt BT_NXT':
      shifted: $$mdi:bluetooth$$
      tap: $$mdi:skip-next$$
    '&bt BT_PRV':
      shifted: $$mdi:bluetooth$$
      tap: $$mdi:skip-previous$$
    # .ro
    '&ro_a_upper':
      tap: Ă
    '&ro_a_lower':
      tap: ă
    '&ro_ai_upper':
      tap: Â
    '&ro_ai_lower':
      tap: â
    '&ro_i_upper':
      tap: Î
    '&ro_i_lower':
      tap: î
    '&ro_s_upper':
      tap: Ș
    '&ro_s_lower':
      tap: ș
    '&ro_t_upper':
      tap: Ț
    '&ro_t_lower':
      tap: ț
#  special ones
    '&my_aA_upper':
      tap: Α
    '&my_aA_lower':
      tap: α
    '&my_bB_upper':
      tap: ∩
    '&my_bB_lower':
      tap: β
    '&my_bBr_upper':
      tap: ⊼
    '&my_bBr_lower':
      tap: ∧
    '&my_bc_upper':
      tap: ≅
    '&my_bc_lower':
      tap: ⋝
    '&my_bo_upper':
      tap: ≠
    '&my_bo_lower':
      tap: ⋜
    '&my_cC_upper':
      tap: ⊂
    '&my_cC_lower':
      tap: χ
    '&my_cC1_upper':
      tap: ≉
    '&my_cC1_lower':
      tap: ≈
    '&my_cCr_upper':
      tap: ⊆
    '&my_cCr_lower':
      tap: ⊄
    '&my_dD_upper':
      tap: ∂
    '&my_dD_lower':
      tap: δ
    '&my_eE_upper':
      tap: ℇ
    '&my_eE_lower':
      tap: ε
    '&my_fF_upper':
      tap: ψ
    '&my_fF_lower':
      tap: φ
    '&my_gG_upper':
      tap: Γ
    '&my_gG_lower':
      tap: γ
    '&my_hH_upper':
      tap: ℋ
    '&my_hH_lower':
      tap: ℏ
    '&my_iI_upper':
      tap: ∮
    '&my_iI_lower':
      tap: ∫
    '&my_jJ_upper':
      tap: ∉
    '&my_jJ_lower':
      tap: ∈
    '&my_kK_upper':
      tap: ∆
    '&my_kK_lower':
      tap: ϰ
    '&my_kK1_upper':
      tap: Å
    '&my_kK1_lower':
      tap: ∝
    '&my_lL_upper':
      tap: Λ
    '&my_lL_lower':
      tap: λ
    '&my_lL1_upper':
      tap: ℒ
    '&my_lL1_lower':
      tap: °
    '&my_mM_upper':
      tap: ∘
    '&my_mM_lower':
      tap: μ
    '&my_nN_upper':
      tap: ∪
    '&my_nN_lower':
      tap: η
    '&my_nNr_upper':
      tap: ⊻
    '&my_nNr_lower':
      tap: ∨
    '&my_oO_upper':
      tap: ⊗
    '&my_oO_lower':
      tap: ∞
    '&my_pP_upper':
      tap: ∏
    '&my_pP_lower':
      tap: π
    '&my_pP1_upper':
      tap: ∓
    '&my_pP1_lower':
      tap: ±
    '&my_qQ_upper':
      tap: ϕ
    '&my_qQ_lower':
      tap: σ
    '&my_qQ1_upper':
      tap: ⋅
    '&my_qQ1_lower':
      tap: ×
    '&my_rR_upper':
      tap: ∇
    '&my_rR_lower':
      tap: ρ
    '&my_sS_upper':
      tap: ⨋
    '&my_sS_lower':
      tap: ∑
    '&my_ss2_upper':
      tap: ≢
    '&my_ss2_lower':
      tap: ≡
    '&my_tT_upper':
      tap: θ
    '&my_tT_lower':
      tap: ϑ
    '&my_uU_upper':
      tap: ℂ
    '&my_uU_lower':
      tap: τ
    '&my_vV_upper':
      tap: ⊃
    '&my_vV_lower':
      tap: χ
    '&my_vVr_upper':
      tap: ⊇
    '&my_vVr_lower':
      tap: ⊅
    '&my_wW_upper':
      tap: Ω
    '&my_wW_lower':
      tap: ω
    '&my_xX_upper':
      tap: Ξ
    '&my_xX_lower':
      tap: ξ
    '&my_xXr_upper':
      tap: Ç
    '&my_xXr_lower':
      tap: ç
    '&my_yY_upper':
      tap: ℤ
    '&my_yY_lower':
      tap: ℝ
    '&my_zZ_upper':
      tap: ∡
    '&my_zZ_lower':
      tap: ζ

  zmk_combos:
    combo_to_2:
      align: top
    combo_to_3:
      align: top
    combo_bt_clear:
      align: top
      offset: 0.03
    combo_mute:
      align: top
      offset: 0.15
    combo_minus:
      key:
        shifted: "_"
        hold: "-"
    combo_equal:
      key:
        shifted: "+"
        hold: "="
    combo_backslash:
      key:
        shifted: "|"
        hold: \
    combo_lbkt:
      key:
        shifted: "{"
        hold: "["
    combo_rbkt:
      key:
        shifted: "}"
        hold: "]"
    combo_semicolon:
      key:
        shifted: ":"
        hold: ";"

  zmk_preamble: '#define KEYMAP_DRAWER'
  zmk_additional_includes: ["zmk-helpers/include"]

draw_config:
  key_w: 80
  key_h: 76
  split_gap: 30.0
  key_rx: 4.0
  key_ry: 4.0
  dark_mode: false
  n_columns: 1
  separate_combo_diagrams: false
  combo_diagrams_scale: 2
  inner_pad_w: 2.0
  inner_pad_h: 2.0
  outer_pad_w: 60.0
  outer_pad_h: 60.0
  line_spacing: 1.0
  arc_radius: 6.0
  append_colon_to_layer_header: false
  small_pad: 2.0
  legend_rel_x: 0.0
  legend_rel_y: 0.0
  draw_key_sides: true
  key_side_pars:
    rel_x: 0
    rel_y: 4
    rel_w: 12
    rel_h: 12
    rx: 4
    ry: 4
  footer_text: Created with <a href="https://github.com/caksoylar/keymap-drawer">keymap-drawer</a>
  shrink_wide_legends: 7
  style_layer_activators: true
  glyph_tap_size: 30
  glyph_hold_size: 16
  glyph_shifted_size: 16
  glyphs: {}
  #
  # Custom CSS
  # svg_style: ''
  #
  svg_extra_style: |

    /* inherit to force styles through use tags */
    /* a lot lifted from https://github.com/minusfive/zmk-config */
    /* font and background color specifications */

    svg.keymap {
        /*
         * ====================
         * Theme Variables
         * ====================
         */

        /* === Colors === */
        --color--mt3--devtty--alpha: #e2e2da;
        --color--mt3--devtty--teal: #27b6b6;
        --color--mt3--devtty--red:  #ba1312;
        --color--mt3--devtty--mod: #cecfc9;
        --color--mt3--devtty--black:  #000000;
        --color--mt3--devtty--yellow: #f4c45a;
        --color--mt3--devtty--blue: #4687d0;

        /*
         * ====================
         * /End Theme Variables
         * ====================
         */

        font-family: SFMono-Regular,Consolas,Liberation Mono,FontAwesome, monospace;
        font-size: 24px;
        font-kerning: normal;
        text-rendering: optimizeLegibility;
        fill: var(--color--mt3--devtty--alpha);
    }

    rect,
    path {
      shape-rendering: geometricPrecision;
    }

    text {
        text-anchor: middle;
        dominant-baseline: middle;
        line-height: 1;
    }
    text.hold {
      text-anchor: middle;
      dominant-baseline: auto;
      font-size: 14px;
    }

    text.shifted {
      text-anchor: middle;
      dominant-baseline: hanging;
      font-size: 14px;
    }


    /* Layer labels */
    text.label {
        font-weight: bold;
        font-size: 36px;
        text-anchor: start;
        paint-order: stroke;
        fill: var(--color--mt3--devtty--black);
        # stroke: var(--color--mt3--devtty--black);
        translate: 0px 0px;
    }

    text.footer {
      text-anchor: end;
      dominant-baseline: auto;
      # stroke: var(--color--mt3--devtty--black);
      fill: var(--color--mt3--devtty--black);
      stroke-width: 2;
      paint-order: stroke;
      translate: 0px 6px;
  
    }


    /* Keys */
    rect.key {
        fill: var(--color--mt3--devtty--alpha);
    }
    rect.combo {
        fill: var(--color--mt3--devtty--alpha);
        stroke: var(--color--mt3--devtty--alpha);
    }
    .tap {
        fill: var(--color--mt3--devtty--black);
    }
    .shifted{
        font-size: 16px;
        text-anchor: middle;
        dominant-baseline: hanging;
        fill: var(--color--mt3--devtty--black);
        translate: 0px 2px;
    }

    .shifted.glyph {
        fill: var(--color--mt3--devtty--black);
    }

    .hold {
        font-size: 16px;
        text-anchor: middle;
        dominant-baseline: ideographic;
        fill: var(--color--mt3--devtty--black);
        translate: 0 -10px;
    }
    .hold.glyph {
        translate: 0 -10px;
    }


    /*
     * Combos
     */
    rect.combo {
        stroke-width: 0;
    }
    path.combo {
        stroke-width: 1;
        stroke: var(--color--mt3--devtty-black);
        fill: none;
    }
    .combo.tap {
        font-size: 16px;
    }
    .combo.shifted {
        font-size: 13px;
        translate: -9px -2px;
    }
    .combo.shifted.glyph {
        translate: -9px -3px;
    }

    /*
     * Transparent, None, and Ghost Keys
     */
    .trans,
    .none,
    .ghost {
      opacity: 0.8;
    }

    /* esc */
    .keypos-0 {
       rect {
        fill: var(--color--mt3--devtty--yellow);
        stroke: var(--color--mt3--devtty--black);
       }
    }

    /* encoder */
    .keypos-13 {
       rect {
        fill: var(--color--mt3--devtty--red);
        stroke: var(--color--mt3--devtty--black);
       }
    }

    /* enter */
    .keypos-39 {
       rect {
        fill: var(--color--mt3--devtty--red);
        stroke: var(--color--mt3--devtty--black);
       }
    }
    
    /* ctrl */
    .keypos-53 {
       rect {
        fill: var(--color--mt3--devtty--teal);
        stroke: var(--color--mt3--devtty--black);
       }
    }

    .keypos-11, .keypos-12, .keypos-14, .keypos-25, .keypos-26, .keypos-27, .keypos-37, .keypos-38, .keypos-40, .keypos-41, .keypos-49, .keypos-50, .keypos-51, .keypos-52,  .keypos-58, .keypos-59, .keypos-60, .keypos-62, .keypos-63, .keypos-64, .keypos-65 {
       rect {
        fill: var(--color--mt3--devtty--teal);
        stroke: var(--color--mt3--devtty--black);
       }
    }

    /*   */
    .keypos-54 {
       rect {
        fill: var(--color--mt3--devtty--teal);
        stroke: var(--color--mt3--devtty--black);
       }
    }

    /* lwr, rse */
    .keypos-55, .keypos-57 {
       rect {
        fill: var(--color--mt3--devtty--teal);
        stroke: var(--color--mt3--devtty--black);
       }
    }

    /* alt */
    .keypos-56, .keypos-61 {
       rect {
        fill: var(--color--mt3--devtty--teal);
        stroke: var(--color--mt3--devtty--black);
       }
    }
