file_format: "1"
id: mlego5x13
name: mlego m65 5x13
type: shield
url: https://gitlab.com/m-lego/m65
requires:
  - blackpill_f401ce
exposes:
  - i2c_encoder
  - i2c_oled
features:
  - keys
  - encoder
  - display
  - underglow
