file_format: "1"
id: mlego5x13
name: mlego m65 5x13 rev5
type: shield
url: mlego.elena.space
requires:
  - seeduino_xiao_rp2040
exposes:
  - i2c_encoder
  - i2c_oled
features:
  - keys
  - encoder
  - display
